// AUTO-GENERATED by scripts/generate-map-outline.mjs from a real Cambodia
// border GeoJSON (low-resolution, 17-point). Do not hand-edit — run
// `npm run gen:map` to regenerate. Coordinates are [x, z] on the map plane
// (north is -z).

/** Simplified Cambodia border, projected to map-plane [x, z]. */
export const CAMBODIA_OUTLINE: [number, number][] = [[-2.536,3.319],[-3.231,2.407],[-4.095,0.599],[-4.5,-1.515],[-3.406,-2.971],[-1.196,-3.305],[0.406,-3.054],[1.816,-2.368],[2.589,-3.575],[4.104,-2.93],[4.5,-1.763],[4.29,0.335],[1.417,1.682],[2.168,2.743],[0.374,2.87],[-1.106,3.575],[-2.536,3.319]];

// Projection constants baked from the same fit, so pins placed by lat/lng line
// up exactly with the outline above.
const LAT_C = 12.528564;
const LNG_C = 104.9813235;
const COS_LAT = 0.976;
const PX_MID = 0;
const PZ_MID = 0;
const SCALE = 1.751;

/** Project a real [lat, lng] onto the map plane as [x, z]. */
export function projectLatLng(lat: number, lng: number): [number, number] {
  const px = (lng - LNG_C) * COS_LAT;
  const pz = -(lat - LAT_C);
  return [(px - PX_MID) * SCALE, (pz - PZ_MID) * SCALE];
}
